import { fmt } from './analyze.js';

const o = (x) => (x.direction === 'Unclear' ? 'Unclear' : `${x.direction} (${x.confidence})`);
const esc = (s) => s.replace(/\|/g, '\\|');

function table(items) {
  const rows = items.map(({ stock: s, a }) =>
    `| ${s.ticker} | ${fmt(s.changePct)} | ${esc(a.catalyst_short)} | ${o(a.outlook.d1)} | ${o(a.outlook.w1)} | ${o(a.outlook.m1)} |`);
  return ['| Stock | Daily Move | Main Catalyst | 1D Outlook | 1W Outlook | 1M Outlook |', '| --- | --- | --- | --- | --- | --- |', ...rows].join('\n');
}

function section({ stock: s, a }) {
  const line = (label, x) => `- ${label}: ${x.direction}${x.direction === 'Unclear' ? '' : ` — ${x.confidence}`}${x.why ? ` · ${x.why}` : ''}`;
  const why = a.why.map((b) => `- ${b.text}${b.src.length ? ` [${b.src.join(', ')}]` : ''}`).join('\n\n');
  const change = a.could_change.length
    ? a.could_change.map((c) => `- ${c.kind === 'upside' ? '▲ Upside' : '▼ Risk'}: ${c.text}`).join('\n\n')
    : '- No scenarios available.';
  const src = a.sources.length
    ? a.sources.map((n, i) => `${i + 1}. ${n.publisher || 'Unknown'}: [${n.title}](${n.url})${n.published ? ` (${n.published.slice(0, 10)})` : ''}${n.read ? ' · read in full' : ''}`).join('\n')
    : '- No supporting sources found.';
  return `### ${s.name} (${s.ticker}) — ${fmt(s.changePct)}

**What happened (fact):**
${s.name} closed at ${s.close.toFixed(2)} ${s.currency} on ${s.sessionDate}, ${fmt(s.changePct)} vs the close of ${s.prevClose.toFixed(2)} on ${s.prevDate}. Context: ${fmt(s.ret5dPct)} over 5 sessions, ${fmt(s.ret1mPct)} over ~1 month${s.volumeRatio ? `, volume ${s.volumeRatio.toFixed(1)}x its prior 20-day average` : ''}.

**Why it happened (AI interpretation of recent sources):**
${why}

**Outlook (AI forecast, not a recommendation):**
${line('Next day', a.outlook.d1)}
${line('Next week', a.outlook.w1)}
${line('Next month', a.outlook.m1)}

**What could change the outlook (evidence: ${a.evidence}):**
${change}

**Sources:**
${src}
`;
}

export function renderReport({ date, movers, bullish, bearish, provider, overview }) {
  const sessionNote = movers.sessionDate === date
    ? `Moves are measured from the ${movers.baselineDate} close to the ${movers.sessionDate} close.`
    : `Requested end date ${date}; the latest session with data is **${movers.sessionDate}**. Moves are measured from the ${movers.baselineDate} close to the ${movers.sessionDate} close.`;
  const liveNote = movers.sessionLive ? ' **The session is still open: moves use live intraday prices, not final closes.**' : '';
  const m = overview.mood;
  const mood = `**Market mood: ${m.sign} ${m.label}** (fact: ${m.advancers} of ${m.advancers + m.decliners} scanned stocks up, average move ${fmt(m.avgChangePct)}).${overview.story ? ` ${overview.story.headline}` : ''}`;
  return `# Daily Market Movers — ${date}

_${sessionNote}${liveNote} Universe: ${movers.scanned} large-cap US-listed stocks. Daily moves are computed from price data (facts); catalysts and outlooks are AI interpretation/forecasts generated by ${provider} from recent news and article text, and are not investment advice._

${mood}

## Top 5 Bullish Movers

${table(bullish)}

## Top 5 Bearish Movers

${table(bearish)}

---

## Bullish — Analysis

${bullish.map(section).join('\n')}
## Bearish — Analysis

${bearish.map(section).join('\n')}
---

_Disclaimer: Automated research summary. Not a Buy/Sell recommendation, price target, or guarantee. Outlooks are probabilistic and based on limited evidence; verify independently before acting._
`;
}
